### ISSUE TITLE
CRITICAL: Incorrect project structure

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#1]
Your Java project is incorrectly structured, and the code therefore will not compile, and your tests won't run. 

All Java projects need to be separated into two folders: `src` and `test`. Inside `src` (pronounced "source") you place all your code, and inside `test` you place all your tests. This way, VSCode and other editors will recognize the files as a Java project and allow you to run the code. 

In order to get the project structure correctly set up, follow the guidance in the [Junit Workshop](https://chalmers.instructure.com/courses/20812/pages/exercise-2022-11-16-junit-workshop?module_item_id=325445) (you can skip the parts about downloading code, you can just use the code you have written in this lab instead).

**Comment by chrille0313** [comment]
This was handled in 46dfa14985fb4436e260c3b86bde412634cae700. @martinjonsson01, please have a look that this change is implemented correctly.

**Comment by martinjonsson01** [comment]
LGTM!
