### ISSUE TITLE
Missing edge case

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#10]
A special-case not mentioned is when the engine power is negative, which is currently allowed. When it's negative, then calling `gas` can lead to decrementing of speed, and vice-versa with `brake`.

https://github.com/Zazmuz/TDA553-lab1/blob/3c699e03906c6ead1f9a6f59f97f84f219ae98cb/lab1reflection.txt#L41

**Comment by Matistjati** [comment]
Fixed in ac925b003896501752de6ac558db6fee8008c75d
