### ISSUE TITLE
TurboCar implementation

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#11]
Right now this class is just keeping track of whether the turbo is turned on or not. It's not actually implementing the behavior of the turbo. 

https://github.com/Zazmuz/TDA553-lab1/blob/0919993c1b6be4f11288c5d7d2ebdaf3533a9f1c/src/Car/TurboCar.java#L7-L21

You've still got this line in Saab, which is what is actually making the car go faster when the turbo is turned on (that is, what TurboCar should be doing!). 

https://github.com/Zazmuz/TDA553-lab1/blob/0919993c1b6be4f11288c5d7d2ebdaf3533a9f1c/src/CarModels/Saab95.java#L18

Your TrimmedCar does this correctly!

**Comment by chrille0313** [comment]
Oops. We simply forgot to do this during the last refactoring. Fixed in: f4cc820ec460501ae43e1e271be413d417586e66
