### ISSUE TITLE
Spaghetti Codebase

### ISSUE THREAD

**Issue by chrille0313** [Zazmuz/TDA553-lab1#13]
So, I've read through our codebase a little and I pretty quickly realised that we have some code smells I think we should fix. Right now we have three different classes: Car, TurboCar and TrimmedCar which all kind of have their own implementation of a car. If we want to create a car with turbo, we simply inherit the TurboCar class. However, let's say that we now want to create a trimmed car that also has turbo. You're not able to inherit multiple classes in Java so at the current state of our codebase, this would be impossible. Also, if we in the future for example wanted to create a boat that also could be trimmed or have a turbo, this "boat" class would have to either reimplement turbo and trim or inherit TurboCar or TrimmedCar in order to get the functionality. The former leads to code repetition and the latter firstly doesn't make sense and secondly will lead to a hierarchical mess. I instead suggest that we use composition and delegation to achieve the same functionality, but in a more scalable way.

**Comment by chrille0313** [comment]
I'm not sure if this is supposed to be and is then handled in future labs, but I suggest we make this change if it isn't.

**Comment by Matistjati** [comment]
You can't do multiple inheritance in java -> java bad 💢. Switch language, easy fix.
But yeah, composition does seem to be the better solution

**Comment by chrille0313** [comment]
Java bad -> do C# omegalul💯

**Comment by chrille0313** [comment]
Mfw C# doesn't do multiple inheritance either 😳

**Comment by Matistjati** [comment]
😔

**Comment by chrille0313** [comment]
658fe5898f1a5c1117ca91bf6727efa565a8359a
