### ISSUE TITLE
CRITICAL: Duplicated code between Scania and CarTransport

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#14]
https://github.com/Zazmuz/TDA553-lab1/blob/1e39eabd0ed88ef6aa11d0ab0e98919d7ae97162/src/VehicleModels/Scania.java#L14-L17
https://github.com/Zazmuz/TDA553-lab1/blob/1e39eabd0ed88ef6aa11d0ab0e98919d7ae97162/src/VehicleModels/CarTransport.java#L22-L25

**Comment by chrille0313** [comment]
Do you have any suggestions on how we would go about extracting the canDrive() factor to the parent-class (TruckWithAngledPlatform) while still keeping the same public interface?

**Comment by chrille0313** [comment]
(Scania and CarTransport should be able to define different speedFactors, while the canDrive() method should be a factor taken care of by the parent class)

**Comment by martinjonsson01** [comment]
> Scania and CarTransport should be able to define different speedFactors

Yes, and they can, by overriding the method. But they *don't* have different speed factors right now, so there is code duplication, which you should move up into the parent class.

> how we would go about extracting the canDrive() factor to the parent-class (TruckWithAngledPlatform) 

I'm not sure I follow. Why would you want to only extract the canDrive() part of the speed factor? The canDrive method is already defined in TruckWithAngledPlatform.

**Comment by chrille0313** [comment]
I feel like a CarTransport and a Scania dumptruck don't behave in the same way speedwise. Therefore, they should be able to have different speedfactors by defining different constants in the getSpeedFactor() method. However, the canDrive() method is something that is shared amongst all vehicles that extend TruckWithAngledPlatform. So the only real code duplication that I think should be refactored is the call to canDrive(), which should be handled by the parent class.

**Comment by chrille0313** [comment]
The only reason that the constants are the same atm is because we are lazy. I think the only code duplication that really matters is the call to canDrive() as explained above.

**Comment by chrille0313** [comment]
With this change 6f8e3068b407c89b1dc7b368ac92a2d0be4a6993, we can't simply extract the whole method to the parent class for example.

**Comment by martinjonsson01** [comment]
>  I think the only code duplication that really matters is the call to canDrive()

Well, no, I see what you mean but you can't have duplicated code like this and defend it by saying "I might want to change it in the future, and then I'll have to do this" - that's entirely speculative. There's a difference between the current requirements and the potential future requirements. You should always design around the currently known requirements, don't over-engineer the code because that will only make it much harder to work with down the road!

> With this change https://github.com/Zazmuz/TDA553-lab1/commit/6f8e3068b407c89b1dc7b368ac92a2d0be4a6993, we can't simply extract the whole method to the parent class for example.

This can be solved in many different ways. The first thing you should consider is whether the canDrive() check belongs in getSpeedFactor(). If the responsibility of the method is to designate a speed factor that decides how fast the vehicle can move, why is it burdened with the secondary responsbility of having to make sure that the vehicle can drive? Try moving the canDrive()-check up into Vehicle instead, separating it entirely from the speed factor.

Another way of solving it would be to have TruckWithAngledPlatform implement the method like so: `return canDrive() ? getEnginePower() : 0;` and have the subclasses specify their actual speed factors: `super.getSpeedFactor() * 0.01` and `super.getSpeedFactor() * 0.02`. This does not solve the separation of concern issue mentioned above, though.

Feel free to solve it one of those ways, but remember that there are no actual requirements stating that they need to have different speed factors. You can imagine that that is the case if you'd like, but be aware that you're making up your own challenge and this is not something we require you to do (although it is a good exercise)!

**Comment by chrille0313** [comment]
> you can't have duplicated code like this and defend it by saying "I might want to change it in the future, and then I'll have to do this" - that's entirely speculative.

That was not what I meant in my previous reasoning. My point was that the getSpeedFactor() method doesn't belong in the parent class since the speed factor shouldn't be the same for all "TruckWithAngledPlatform".

> The first thing you should consider is whether the canDrive() check belongs in getSpeedFactor(). If the responsibility of the method is to designate a speed factor that decides how fast the vehicle can move, why is it burdened with the secondary responsbility of having to make sure that the vehicle can drive?

This, however, is exactly what I was trying to get to. My point was that this "check" didn't belong there at all, but was wondering what the best way to extract this functionality to the parent class would be.

> Another way of solving it would be to have TruckWithAngledPlatform implement the method like so: return canDrive() ? getEnginePower() : 0; and have the subclasses specify their actual speed factors: super.getSpeedFactor() * 0.01 and super.getSpeedFactor() * 0.02

I believe this is the exact solution I was looking for because this eliminates the need for any child-classes to even think of canDrive(), while also letting them define their own speedfactor without redefining any public interfaces. I didn't know that it is possible to call the overriden method from the overriding one.

**Comment by chrille0313** [comment]
I believe this commit eliminated all code duplication: a94da2afc5cfde9710afe3b4f552f2e02dd99772
