### ISSUE TITLE
Vehicle's location does not change when CarTransport moves

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#16]
The Vehicle instances that are stored within CarTransporter are not moved when the CarTransport moves.

https://github.com/Zazmuz/TDA553-lab1/blob/1e39eabd0ed88ef6aa11d0ab0e98919d7ae97162/src/VehicleModels/CarTransport.java#L10

**Comment by chrille0313** [comment]
12a4c432480ea9a9024a516b41eee06a55349b5e
