### ISSUE TITLE
CRITICAL: Duplicated code between CarTransport and CarRepairShop

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#17]
You've got a lot of duplicated code here. Although the conditions vary a bit, they're mostly the same and so the commonalities can be extracted, while the unique conditions can be left outside.

Try using composition and delegation here.

In the future, whenever you're copying code like this (CarRepairShop says "Car transport is already full!" 🤔), stop and think for a second about whether you can rethink the design in a way that this code does not have to be duplicated!

https://github.com/Zazmuz/TDA553-lab1/blob/1e39eabd0ed88ef6aa11d0ab0e98919d7ae97162/src/VehicleModels/CarTransport.java#L43-L73
https://github.com/Zazmuz/TDA553-lab1/blob/1e39eabd0ed88ef6aa11d0ab0e98919d7ae97162/src/CarRepairShop.java#L30-L53

**Comment by Matistjati** [comment]
Fixed in a9324a9cc333eac8576197b2f7a7495ee4de8139
Personally, I don't think it was worth writing ~140 lines of code to deduplicate around 10 lines, but maybe that's just me :)

**Comment by martinjonsson01** [comment]
Please don't close critical issues. I'll close them once I deem you've resolved them. :)

> Personally, I don't think it was worth writing ~140 lines of code to deduplicate around 10 lines, but maybe that's just me :)

I understand what you mean, and sometimes you're right, sometimes it's better to have some minor code duplication over having a convoluted design just to deduplicate the code! 

But I don't agree on you judging effort by lines of code, because that's actually quite backwards. It does not take much effort to type lines of code, what *does* take effort is thinking about the design and how it should all fit together. You might spend a week discussing designs that turn out to be only 100 lines of code, but that'll save you hours upon hours of work in the future. You often find yourself spending hours figuring out the mathematics behind two lines of code! 

Now, I understand if removing this duplication was difficult because you're not used to working with composition and delegation just yet, but that's exactly why we want you to spend time doing it. By removing these "10 lines" of duplicated code, you've gained the benefits of:
* not having to go to multiple places to make changes to the business requirements (for example, vehicles should be moving at 0.1 speed before being able to be loaded), which means you've eliminated the need for "shotgun programming";
* not having to duplicate code even further whenever you want to create a new class that wants to store vehicles;
* separating out the concerns of the classes so that CarTransport and CarRepairShop now only contain code actually related to their responsibilities, meaning it is much more easy to work with and reason about these classes;
* extracted relatively complex (in that it has many different modes of failure) functionality into its own class, which can then be unit tested on its own.

So while I do realize that it is a bit frustrating to have to put in this much effort in order to deduplicate a small piece of code, it's a very valuable skill which you'll find very helpful down the road, and the main reason you're doing it is not to get rid of the duplicated code, it's because of the points mentioned above. The duplicated code is just the visible artifact indicating these underlying design problems.

As an aside, most of these 135 lines of code are actually made up out of whitespace, method declarations, curly braces and imports. If you count the actually meaningful lines of code you've got around 40, which is very little. This is yet another reason why juding effort by lines of code is quite counter-productive.

**Comment by martinjonsson01** [comment]
Looks good.

Smart solution taking advantage of the `Collection` interface! One problem though, is that `storedVehicles` is never initialized in `VehicleStorage`, only in its subclasses. The way it's written now it's fine, since `VehicleStorage` is abstract, but it's very easy to forget to do `this.storedVehicles = new X<Vehicle>();` in the subclass' constructor, which will lead to a bunch of NullPointerExceptions. To prevent this from accidentally occurring, it's better to require that an instance of `Collection<Vehicle>` is passed into `VehicleStorage`'s constructor, meaning every subclass *has* to give it a non-null value, enforced by the compiler.

You're missing a few `@Override`, which makes it a bit unclear which methods are from the parent class and not:
https://github.com/Zazmuz/TDA553-lab1/blob/a9324a9cc333eac8576197b2f7a7495ee4de8139/src/VehicleMods/Storages/HeapVehicleStorage.java#L16-L25
https://github.com/Zazmuz/TDA553-lab1/blob/a9324a9cc333eac8576197b2f7a7495ee4de8139/src/VehicleMods/Storages/StackVehicleStorage.java#L16-L27

**Comment by chrille0313** [comment]
> To prevent this from accidentally occurring, it's better to require that an instance of Collection<Vehicle> is passed into VehicleStorage's constructor, meaning every subclass has to give it a non-null value, enforced by the compiler.

Very good point. I'm surprised that we didn't actually do this since it seems like the standard way we usually do this kinds of stuff.

> You're missing a few @Override

Totally missed that too. Will be fixed soon!
