### ISSUE TITLE
CRITICAL: Misunderstanding of Liskov Substitution Principle

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#18]
> (Language Server Protocol)

While LSP can stand for this as well, it almost always stands for Liskov Substitution Principle in the context of object-oriented software design. 

https://github.com/Zazmuz/TDA553-lab1/blob/1e39eabd0ed88ef6aa11d0ab0e98919d7ae97162/lab2reflection.txt#L2-L15

>The contract here is between the different car models and the 
     superClass car. The contract is based around a need to know basis 
     where we try to keep as many things private as possible.

That's too wide of a definition of "contract". What we're asking about here is the *method contract of gas() and brake()*, not the relation between Vehicle and the car models. 

> The clients expect gas to accelerate the car, and break to deaccelerate it. 

Okay, given that contract definition, take a look at what this code does:
https://github.com/Zazmuz/TDA553-lab1/blob/1e39eabd0ed88ef6aa11d0ab0e98919d7ae97162/src/Vehicle.java#L81-L99
Now, what happens in the above code when the following override is applied?
https://github.com/Zazmuz/TDA553-lab1/blob/1e39eabd0ed88ef6aa11d0ab0e98919d7ae97162/src/VehicleModels/Scania.java#L14-L17

Given that contract, it is being broken by Scania and CarTransport, and therefore LSP is being broken. 

Can you find a way to make your design follow the LSP? (Hint: This does not involve changing the code at all.)

**Comment by Zazmuz** [comment]
We have looked it over, removed the joke about Language Server Protocol, rethought our gas contract slightly to accommodate the override which means that gas only does something when its allowed to. Meaning for example that the engine has to be on or that the AngledPlatform has to be closed.

**Comment by martinjonsson01** [comment]
> removed the joke about Language Server Protocol

I figured as much, but I had to clarify just in case there was an actual misunderstanding. 😛
