### ISSUE TITLE
"Planning for the future"

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#19]
You say that this is probably some design principle, but in fact it is the opposite. The principle applicable here is YAGNI ("You Aren't Gonna Need It").

While making the code today future-proof might sound good, it often overcomplicates the design unnecessarily. Often times requirements change in a way you can't predict, and therefore it is often a better idea to wait with implementing things until you actually know what you need. If you start implementing things before you need them, then this is what is known as [speculative generality](https://refactoring.guru/smells/speculative-generality). 

Note that this isn't to say that making well-designed code from the beginning is something you should avoid doing, rather you should do it at a reasonable level. It's easy to go overboard with complicated designs when all you need is a simple implementation right now.

(This issue is just mentioning things to keep in mind in the future, nothing for you to change or fix.)

https://github.com/Zazmuz/TDA553-lab1/blob/1e39eabd0ed88ef6aa11d0ab0e98919d7ae97162/lab2reflection.txt#L29

**Comment by Matistjati** [comment]
I completely agree on the point that you need to find a balance. If we didn't want to plan for the future at all, it would be easier to just copy-paste the code and not be DRY. However, adding ways to deduplicate code also creates its own sort of complexity with harder to follow information and code flows. I'll try my best during the course to find a reasonable balance between the two.
