### ISSUE TITLE
Split work into multiple commits

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#2]
It seems like you have made very few, but big, commits. You have done okay naming them, but you can't be very specific in the commit message as they contain so much. 

If you find yourself not being able to summarize your changes into a single sentence that you can use as a commit message, then you have included too much work in that single commit, and it should be split up among several. The reason for this is that it is much easier for others to track your progress and see in which order you made certain changes - which is very helpful for future reference (both for yours and others' sake!). 

Also, things like "fixed stuff" or "Done for the day" have little to no meaning to any future person looking at what you have done. Instead, try to describe what you have done in the commit. Something like "Resolved bug involving incorrect date format" or "Implemented support for .yaml configuration files".

[Added reflection and fixed up the code.](https://github.com/Zazmuz/TDA553-lab1/commit/bf53fc14428fb1d43950f5dd142341057b865783)
[Worked through steps 1-4](https://github.com/Zazmuz/TDA553-lab1/commit/f07a44631492e2a553983d37ef8f7bed0dbeb0a0)

**Comment by Matistjati** [comment]
We'll try to keep that in mind in the future :)
