### ISSUE TITLE
Naming of packages

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#20]
In Java, we generally name packages in all lower-case, to distinguish them from classes with are PascalCase.

Also, `src` should not be a package. It's a folder present in all Java-projects (`test`, too), but it's not a package itself.

https://github.com/Zazmuz/TDA553-lab1/blob/a9324a9cc333eac8576197b2f7a7495ee4de8139/src/CarRepairShop.java#L3

**Comment by chrille0313** [comment]
> Also, src should not be a package. It's a folder present in all Java-projects (test, too), but it's not a package itself.

I'm not sure I follow. How are we supposed to handle imports between files in src? (If i remove package src, then Intellij doesn't find the other files)

**Comment by martinjonsson01** [comment]
It's a common misunderstanding due to the way IDEs misinterpret your file structure sometimes. When you don't specify a package for a class (which you don't for source files located directly at the root of `src`), then that class is placed into the default package. The default package is imported by ~~all files in the project~~ all files in the default package automatically, and so you don't need to manually import it. 

Sometimes it takes a while for the IDEs to understand that you've changed the package structure, so after doing it you might have to restart your IDE in order for it to recognize the new structure.

**Comment by chrille0313** [comment]
Oh, I hade the project root set as source and not the src-folder. However, it seems like you can't import classes from the default package into other packages. Is the convention that each class is wrapped in its own folder?

**Comment by martinjonsson01** [comment]
Sorry, I should have clarified. Only classes within the default package automatically import from the default package. 

The default package is there to simplify the creation of smaller programs with only a few number of files. For larger projects, you always have your own root package (usually named after your organization/company). So the convention is to not use the default package, that is, you don't put any source files directly in the `src` directory.

**Comment by chrille0313** [comment]
> So the convention is to not use the default package, that is, you don't put any source files directly in the src directory.

So for example, the "Movable" interface should be placed in a folder/package called "Movable"?

**Comment by martinjonsson01** [comment]
No, you almost never want to name a package directly after a specific concrete type. Packages are collections of cohesive source files, so you want them to give semantic information about the classes within. Simply wrapping every single source file in a package named after itself is entirely redundant. 

The `Movable` interface belongs in the same package as where it is used. 

Usually you don't create packages when you've only got a single type to put in them. Only when you've got a collection of multiple types that you have decided should be contained within a single module - then you create a package for them!

**Comment by martinjonsson01** [comment]
Think of every package as one contained unit, or module. There's a reason the default visibility in Java is package-private. You often want methods and classes to be visible within the same package, but not to the outside world. Only a few specific classes are meant to be `public` and open to the outside world.

**Comment by chrille0313** [comment]
So, after your suggestions + some googling, I came up with the following structure: b69e7d84c906b4c57b9e93ca5b4d10afb1cc539a. However, I'm not able to make the tests work (java: package org.junit does not exist).

**Comment by martinjonsson01** [comment]
Have you configured your source and test roots correctly?  

Side note: compound names like `vehicle_mods` and `vehicle_models` aren't really used in package naming, you usually don't allow non-alphabetical characters like "_". This is because packages are supposed to form a meaningful hierarchy, so you would want `vehicles.mods` rather than `vehicle_mods` as a standalone-package.

**Comment by chrille0313** [comment]
> Have you configured your source and test roots correctly?

I thought I did. I have "src" as sources-root and test as "tests-root". But I noticed that if I move test out one step, then everything works again. Should I leave it like this or set "main" as sources root (I think that will resolve the issue as well)

**Comment by martinjonsson01** [comment]
If it resolves the issue setting main as the sources root, then do that. Since it's just an IntelliJ-specific thing it doesn't really affect the project structure.

**Comment by chrille0313** [comment]
#22

**Comment by chrille0313** [comment]
Are we allowed to close non-critical issues ourselves?

**Comment by martinjonsson01** [comment]
Yes!
