### ISSUE TITLE
Breaking of LSP

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#21]
Overriding a method and throwing an exception because you don't want it implemented explicitly breaks the Liskov Substitution Principle.

You don't have to fix it, as you've already demonstrated knowledge about LSP, but please be aware that you're breaking it here.

https://github.com/Zazmuz/TDA553-lab1/blob/a9324a9cc333eac8576197b2f7a7495ee4de8139/src/VehicleMods/Storages/HeapVehicleStorage.java#L21-L23

**Comment by chrille0313** [comment]
We were aware that this is breaking LSP. But at the time we couldn't come up with a better way of doing what we wanted, since the different storages implement removeFromStorage() differently (different arguments). Do you have any suggestions?

**Comment by martinjonsson01** [comment]
If the different types of storages do not share a common interface, then you should not force a common interface upon them. Don't place any `removeFromStorage` methods in the parent class, since you don't know which one the subclass will want.

**Comment by chrille0313** [comment]
But we still expect any storage to have some removeFromStorage method in the public interface

**Comment by martinjonsson01** [comment]
Yes, but unless you can specify "some removeFromStorage" through the type system, then you can't put it in the parent's interface without forcing a subclass to break LSP or implement both of them. 

You have named these two methods the same thing, and simply overloaded it, which is fine. But this might be confusing things since they actually do different things. One is `removeThisSpecificCarFromStorage(Car c)` and the other is `removeThePredeterminedCarFromStorage`, which are two methods with two different contracts.

**Comment by Matistjati** [comment]
That makes sense, without a common contract we shouldn't force an abstract method for each implementation. This mirrors how collection does it too- it doesn't always make sense to offer a "remove at the front" or "remove at this index" for all data structures.

**Comment by martinjonsson01** [comment]
Exactly!

**Comment by chrille0313** [comment]
Is this better? 593dbb1afa7fac61b9d6a7eab6a2bd9adcb0b7f7

**Comment by martinjonsson01** [comment]
Yes, it no longer breaks LSP.
