### ISSUE TITLE
SRP: Use an Application class for the main method

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#23]
Right now CarController has both the responsibility of starting/bootstrapping the program and performing it's controller duties.

https://github.com/Zazmuz/TDA553-lab1/blob/582e70356f37d34bb0b5fad2886b600253746b7c/src/main/Controller/CarController.java#L47-L50

**Comment by Matistjati** [comment]
Fixed in bed750ec0ccc91dfbc8123d44d82601406b0e492
