### ISSUE TITLE
Violation of OCP

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#24]
https://github.com/Zazmuz/TDA553-lab1/blob/582e70356f37d34bb0b5fad2886b600253746b7c/src/main/Controller/CarController.java#L52-L63

**Comment by Matistjati** [comment]
Fixed in 41dc64c101f92a1e92f2d77b5bd1e1bb9996bb81 (see CarController)

**Comment by Zazmuz** [comment]
(this was nice)

**Comment by martinjonsson01** [comment]
Looks good in CarController, but you've only moved the problem into Controller:
https://github.com/Zazmuz/TDA553-lab1/blob/fd8be87be46cc441ed00da58acaa1b1b0d4002f3/src/main/Controller/Controller.java#L49-L60

So it still violates OCP.

**Comment by Matistjati** [comment]
How would you fix it? Using this, we can easily extend Controller to change the behaviour of each event.

**Comment by martinjonsson01** [comment]
If you wanted to add a new button, you'd have to modify Controller. So while it's true that it's closed for modification when modifying the behavior of the existing events, it's not closed for modification when extending with new buttons. 

I think the underlying problem here is one of Separation of Concern. You shouldn't have a single Controller-class in charge of all of the buttons of the entire app, you should have multiple separate controllers.
