### ISSUE TITLE
Violation of Law of Demeter

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#25]
https://github.com/Zazmuz/TDA553-lab1/blob/582e70356f37d34bb0b5fad2886b600253746b7c/src/main/Controller/CarController.java#L41
https://github.com/Zazmuz/TDA553-lab1/blob/582e70356f37d34bb0b5fad2886b600253746b7c/src/main/views/WorldView.java#L52
https://github.com/Zazmuz/TDA553-lab1/blob/582e70356f37d34bb0b5fad2886b600253746b7c/src/main/views/WorldView.java#L170
https://github.com/Zazmuz/TDA553-lab1/blob/582e70356f37d34bb0b5fad2886b600253746b7c/src/main/views/WorldView.java#L163

**Comment by Matistjati** [comment]
Fixed in 41dc64c101f92a1e92f2d77b5bd1e1bb9996bb81 (?)
