### ISSUE TITLE
Encapsulation: Instance fields should be private

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#26]
https://github.com/Zazmuz/TDA553-lab1/blob/582e70356f37d34bb0b5fad2886b600253746b7c/src/main/views/WorldView.java#L29
https://github.com/Zazmuz/TDA553-lab1/blob/582e70356f37d34bb0b5fad2886b600253746b7c/src/main/views/WorldView.java#L34-L49
https://github.com/Zazmuz/TDA553-lab1/blob/582e70356f37d34bb0b5fad2886b600253746b7c/src/main/world/World.java#L15-L16

**Comment by Matistjati** [comment]
Fixed in fd8be87be46cc441ed00da58acaa1b1b0d4002f3
