### ISSUE TITLE
Naming: Methods should begin with lower case letters

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#27]
This is to distinguish them from types, that begin with capital letters.

https://github.com/Zazmuz/TDA553-lab1/blob/582e70356f37d34bb0b5fad2886b600253746b7c/src/main/views/WorldView.java#L128
https://github.com/Zazmuz/TDA553-lab1/blob/582e70356f37d34bb0b5fad2886b600253746b7c/src/main/views/WorldView.java#L86

**Comment by Matistjati** [comment]
Fixed in e3b64f4924e1f8f78c2441b315e744a38a192982
