### ISSUE TITLE
CRITICAL: MVC: This code should be in one or more of the Controllers, because it is about taking input from the user, not telling the user the state of the model.

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#28]
(Hint; It will be easiest if you make all the code relating to the buttons and spinner into Controllers.)

https://github.com/Zazmuz/TDA553-lab1/blob/582e70356f37d34bb0b5fad2886b600253746b7c/src/main/views/WorldView.java#L128-L173

**Comment by Matistjati** [comment]
Fixed in 41dc64c101f92a1e92f2d77b5bd1e1bb9996bb81 and f524517632134fc0225d5a40116a20b5d88c9a67

**Comment by martinjonsson01** [comment]
Nicely done!
