### ISSUE TITLE
Bad practice: Not using @Override

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#3]
When overriding methods from interfaces or classes, always add `@Override` on top of them. Although this is not required by the compiler, it's helpful for both IDEs and people to more easily identify that these methods are overriden. (This also comes with the added benefit of the compiler telling you if you're not actually overriding anything, for example if you've misspelled the method name!)

https://github.com/Zazmuz/TDA553-lab1/blob/3c699e03906c6ead1f9a6f59f97f84f219ae98cb/Car.java#L23-L36

**Comment by chrille0313** [comment]
Small miss. Issue fixed in following commit: b9c75c5410ff2f27f43dab793e2d9958e626f03c
