### ISSUE TITLE
DIP: It would be better to use the more abstract type List<Vehicle> as the static type instead of ArrayList<Vehicle>

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#30]
https://github.com/Zazmuz/TDA553-lab1/blob/582e70356f37d34bb0b5fad2886b600253746b7c/src/main/world/World.java#L16
https://github.com/Zazmuz/TDA553-lab1/blob/582e70356f37d34bb0b5fad2886b600253746b7c/src/main/world/World.java#L23-L25

**Comment by Matistjati** [comment]
Fixed in 4fc308b070da53295b70f09c626624221d1ed363
