### ISSUE TITLE
Avoid null

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#31]
A cleaner way of handling this is to initialize the variable to an empty list. Then the for-loop will do nothing at all, and you don't need the null-check.

https://github.com/Zazmuz/TDA553-lab1/blob/582e70356f37d34bb0b5fad2886b600253746b7c/src/main/views/ObjectView.java#L24
https://github.com/Zazmuz/TDA553-lab1/blob/582e70356f37d34bb0b5fad2886b600253746b7c/src/main/views/ObjectView.java#L31-L32

**Comment by Matistjati** [comment]
Fixed in ddf29aea3eef38313d0a3df4449208c9fd360871
