### ISSUE TITLE
CRITICAL: Duplicated code remains in Volvo and Saab

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#4]
https://github.com/Zazmuz/TDA553-lab1/blob/3c699e03906c6ead1f9a6f59f97f84f219ae98cb/Volvo240.java#L17-L23
https://github.com/Zazmuz/TDA553-lab1/blob/3c699e03906c6ead1f9a6f59f97f84f219ae98cb/Saab95.java#L24-L30

**Comment by Matistjati** [comment]
Fixed in b3c864b1a923fb0d91955eacfe23d5bc365c1929
Made cleaner using a setter for currentspeed

**Comment by martinjonsson01** [comment]
@Matistjati please do not close the critical issues yourselves. I'll close them when I find that you've fixed them, as per the submission guidelines:
"Your grader will close any issues that have been resolved, or update the issue with feedback on why the changes do not resolve the issue."
