### ISSUE TITLE
OCP: Trim composition

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#6]
It might be better to put the code involving trim into its own class which Volvo240 inherits from or delegates to. Then we could create a new car with trim without modifying or duplicating code.

https://github.com/Zazmuz/TDA553-lab1/blob/3c699e03906c6ead1f9a6f59f97f84f219ae98cb/Volvo240.java#L5

**Comment by Matistjati** [comment]
Fixed using inheritance in 0919993c1b6be4f11288c5d7d2ebdaf3533a9f1c

**Comment by martinjonsson01** [comment]
Note that you can do this using composition and delegation instead, which is a better solution than inheritance!
