### ISSUE TITLE
CRITICAL: Breaking interface changes

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#7]
When dealing with public interfaces, you often have many people depending on them. This means that any change you make to them will affect many users, so you should only ever do so when absolutely necessary. 

Here you have changed all three interface methods from what is described in task 2. Please change them back. 

(Your implementation can have a fixed turning rate, the user does not need to specify how much they want to turn.)
(The current speed should be known by the class being moved, you should not have to pass the speed in when calling move.)

https://github.com/Zazmuz/TDA553-lab1/blob/3c699e03906c6ead1f9a6f59f97f84f219ae98cb/Movable.java#L2-L10

**Comment by chrille0313** [comment]
I totally agree with your point on the move method. However, I think it makes sense to specify a "turning amount" that is a percentage of your turning rate (you don't always turn the wheel fully to the left/right). If we want to implement this feature, would the correct approach instead be to add a method called something like "steerLeft" and update the state in the Car-class to keep track of our current turning rate (Like gas() is a wrapper for move())? Or is making default arguments through overloading a better approach? Which one would you argue is best practise?

**Comment by chrille0313** [comment]
Your suggestions are implemented here btw: b0882b1326718107997ee2f9cf38476493143ccf

**Comment by martinjonsson01** [comment]
> However, I think it makes sense to specify a "turning amount" 
I agree! But that's not the issue here. The issue here, and the point I'm making, is that usually you have to stick to the interfaces given - you can't just change them whenever you feel like you've got a better idea. 

Of course, this isn't to say that you can never change interfaces. You often change them in reality, but you should only ever do so after careful consideration of the implications of the change. If you've got a lot of code depending on this interface, then a lot of code will have to be refactored to fit your new version of the interface. This takes a lot of time, and isn't always worth it (though sometimes it is!). 

> If we want to implement this feature, would the correct approach instead be to add a method called something like "steerLeft"

If by this you mean that you'll add `steerLeft(double degrees)` in addition to the existing `turnLeft()` present in the interface, then yes that is correct. You still want to implement the agreed-upon interface (so that code that doesn't know about your code, and only knows about the interface, can still call your code!), but you're free to implement other ways of controlling in addition to what is required by the interface. 

> Like gas() is a wrapper for move()

Maybe I didn't catch this last time, but that sounds wrong. `gas()` is supposed to accelerate the car, not move it. That's what the `move()` method is for. If you are calling `move()` inside of `gas()` then that's an unknown side-effect, which can be very confusing to people calling your code. Imagine, for instance, if I wanted to rev the engine at the beginning of a race, so I call `gas()` many times, in order to prepare for take-off. In that case I would not like it if the car were to move when I was simply accelerating. 

Now, on the other hand, what I just mentioned is one way of looking at it, but it's up to you how you choose to design this system. If you wanted to have the acceleration always be coupled to movement, then that's a valid choice *as long as it is clearly documented!*

> Or is making default arguments through overloading a better approach? 

Having an overload of `turnLeft` available that allows the caller to pick how much to turn is a good way of doing it. Then you'd have both `turnLeft()` and `turnLeft(double angle)`. These do not necessarily both have to be in the interface `Movable`. Maybe you only want to offer the fixed `turnLeft()` method through the interface, then you'd put the angle-overload inside the class but not the interface. You could also choose to have it inside the interface, since adding methods to an interface is a lot less dangerous than modifying or removing them (but once you've added it, it's hard to take it back!).

> Which one would you argue is best practise?

I think using method overloading here seems like the most idiomatic way of doing it, since you've got the same behavior that can be controlled with different levels of detail.
