### ISSUE TITLE
CRITICAL: Missing tests for turnRight

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#8]
You have only tested `turnLeft`, never `turnRight`.

https://github.com/Zazmuz/TDA553-lab1/blob/3c699e03906c6ead1f9a6f59f97f84f219ae98cb/CarTests.java#L7

**Comment by Matistjati** [comment]
Fixed in 8750da3585d56eb27841e4615e353876a011da9a
