### ISSUE TITLE
Encapsulation: Instance variables should be private

### ISSUE THREAD

**Issue by martinjonsson01** [Zazmuz/TDA553-lab1#9]
Unless required by the subclasses, instance variables should be private. This is to hide implementation details, which allows the class to be changed in the future without impacting any subclasses or other clients. It also controls access to them, as they can then only be accessed through getters and setters, which can contain bound checks and other similar controls.

https://github.com/Zazmuz/TDA553-lab1/blob/3c699e03906c6ead1f9a6f59f97f84f219ae98cb/Car.java#L5-L13

**Comment by Matistjati** [comment]
Fixed in b3c864b1a923fb0d91955eacfe23d5bc365c1929
